# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-03 19:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_auto_20180203_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_url', models.CharField(max_length=200, verbose_name='视频地址')),
                ('is_adopt', models.BooleanField(default=False, verbose_name='是否通过')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='讲师用户')),
            ],
            options={
                'verbose_name': '上传视频',
                'verbose_name_plural': '上传视频',
            },
        ),
    ]
