# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-03 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_teacherupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherupload',
            name='upload_url',
            field=models.URLField(verbose_name='视频地址'),
        ),
    ]
