# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20180204_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherupload',
            name='course',
            field=models.CharField(default=1, max_length=30, verbose_name='课程'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherupload',
            name='lesson',
            field=models.CharField(default=1, max_length=30, verbose_name='章节'),
            preserve_default=False,
        ),
    ]
