# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_bannercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='选择题目')),
                ('choice', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], max_length=5, verbose_name='选项')),
                ('students', models.IntegerField(default=0, verbose_name='练习人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('learn_times', models.IntegerField(default=0, verbose_name='建议练习时长(分钟数)')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('image', models.ImageField(max_length=128, upload_to='practice/%Y/%m', verbose_name='封面图')),
                ('analysis', models.TextField(verbose_name='答案解析')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节')),
            ],
            options={
                'verbose_name': '选择题库',
                'verbose_name_plural': '选择题库',
            },
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='选择题目')),
                ('desc', models.TextField(verbose_name='题目描述')),
                ('analysis', models.TextField(verbose_name='解题思路')),
                ('students', models.IntegerField(default=0, verbose_name='练习人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('download', models.FileField(max_length=128, upload_to='pracitce/resource/%Y/%m', verbose_name='项目文件')),
                ('image', models.ImageField(max_length=128, upload_to='practice/%Y/%m', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节')),
            ],
            options={
                'verbose_name': '选择题库',
                'verbose_name_plural': '选择题库',
            },
        ),
    ]
