# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-06 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(max_length=50, verbose_name='选项题目')),
                ('choiceA', models.CharField(max_length=50, verbose_name='选项A')),
                ('choiceB', models.CharField(max_length=50, verbose_name='选项B')),
                ('choiceC', models.CharField(max_length=50, verbose_name='选项C')),
                ('choiceD', models.CharField(max_length=50, verbose_name='选项D')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='选择题目')),
                ('desc', models.CharField(blank=True, max_length=120, null=True, verbose_name='题库描述')),
                ('students', models.IntegerField(default=0, verbose_name='练习人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('degree', models.SmallIntegerField(choices=[(0, '易'), (1, '中'), (2, '难')], default=0, verbose_name='难度')),
                ('pratice_times', models.IntegerField(default=0, verbose_name='建议练习时长(分钟数)')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('image', models.ImageField(max_length=128, upload_to='practice/%Y/%m', verbose_name='封面图')),
                ('analysis', models.TextField(verbose_name='答案解析')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节')),
            ],
            options={
                'verbose_name': '选择题库',
                'verbose_name_plural': '选择题库',
            },
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='选择题目')),
                ('desc', models.TextField(verbose_name='题目描述')),
                ('analysis', models.TextField(verbose_name='解题思路')),
                ('students', models.IntegerField(default=0, verbose_name='练习人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('download', models.FileField(max_length=128, upload_to='pracitce/resource/%Y/%m', verbose_name='项目文件')),
                ('image', models.ImageField(max_length=128, upload_to='practice/%Y/%m', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节')),
            ],
            options={
                'verbose_name': '编程题库',
                'verbose_name_plural': '编程题库',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='choicequestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.ChoiceQuestion', verbose_name='选择题目'),
        ),
    ]
