# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicequestion',
            old_name='learn_times',
            new_name='pratice_times',
        ),
    ]
