# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-06 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice', '0002_auto_20180206_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '错题集',
                'verbose_name_plural': '错题集',
            },
        ),
        migrations.AlterField(
            model_name='choice',
            name='choicequestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.ChoiceQuestion', verbose_name='题库题目'),
        ),
        migrations.AddField(
            model_name='errorquestion',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.Choice', verbose_name='选择题'),
        ),
        migrations.AddField(
            model_name='errorquestion',
            name='choicequestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.ChoiceQuestion', verbose_name='题库题目'),
        ),
        migrations.AddField(
            model_name='errorquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
