# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20180201_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(max_length=50, verbose_name='选项题目')),
                ('choice', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], max_length=5, verbose_name='选项')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
        migrations.AlterModelOptions(
            name='programming',
            options={'verbose_name': '编程题库', 'verbose_name_plural': '编程题库'},
        ),
        migrations.RemoveField(
            model_name='choicequestion',
            name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.ChoiceQuestion', verbose_name='选择题目'),
        ),
    ]
