# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 13:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20180201_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
