# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-06 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_auto_20180206_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorquestion',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
