# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_choice_add_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='title',
            new_name='choicequestion',
        ),
    ]
