# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_auto_20180201_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicequestion',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='programming',
            old_name='Course',
            new_name='course',
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='degree',
            field=models.SmallIntegerField(choices=[(0, '易'), (1, '中'), (2, '难')], default=0, verbose_name='难度'),
        ),
    ]
