# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_auto_20180201_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='desc',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='题库描述'),
        ),
    ]
