# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_choicequestion_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceA',
            field=models.CharField(default=1, max_length=50, verbose_name='选项A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceB',
            field=models.CharField(default=1, max_length=50, verbose_name='选项B'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceC',
            field=models.CharField(default=1, max_length=50, verbose_name='选项C'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='choiceD',
            field=models.CharField(default=1, max_length=50, verbose_name='选项D'),
            preserve_default=False,
        ),
    ]
