# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180122_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[(0, '注册'), (1, '找回密码'), (2, '修改邮箱')], max_length=10, verbose_name='发送类型'),
        ),
    ]
